services:
  worker-sdxl-turbo:
    image: runpod/worker-sdxl-turbo:dev
    pull_policy: never

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    ports:
      - "8000:8000"

    volumes:
      - ./var/runpod-volume:/runpod-volume
